Toda criação de tabela a seguir 
    
CREATE TABLE CLIENTE (
    CLIENTEID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    EMAIL VARCHAR2(100),
    DATA_CADASTRO DATE
);

CREATE TABLE CATEGORIAS (
    CATEGORIAID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100)
);

CREATE TABLE PRODUTOS (
    PRODUTOID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    PRECO NUMBER(10,2),
    CATEGORIA_ID NUMBER,
    ESTOQUE NUMBER
);

CREATE TABLE PEDIDOS (
    PEDIDOID NUMBER PRIMARY KEY,
    CLIENTEID NUMBER,
    DATAPEDIDO DATE,
    STATUS VARCHAR2(30),
    VALORTOTAL NUMBER(10,2)
);

CREATE TABLE ITENSPEDIDOS (
    ITEMID NUMBER PRIMARY KEY,
    PEDIDOID NUMBER,
    PRODUTOID NUMBER,
    QUANTIDADE NUMBER,
    PRECOUNITARIO NUMBER(10,2)
);

CREATE TABLE PAGAMENTOS (
    PAGAMENTOID NUMBER PRIMARY KEY,
    PEDIDOID NUMBER,
    STATUSPAGAMENTO VARCHAR2(30),
    DATAPAGAMENTO DATE
);
