-- Alguns exemplos de INSERT utilizados para popular o banco de dados do projeto de e-commerce
  
INSERT INTO CATEGORIAS (CATEGORIASID, NOME)
VALUES (1, 'Eletronico');

INSERT INTO CATEGORIAS (CATEGORIASID, NOME)
VALUES (2, 'Roupa');

INSERT INTO CLIENTE (CLIENTEID, NOME, EMAIL)
VALUES (1, 'Lana Mendes', 'lanamendes@gmail.com');

INSERT INTO CLIENTE (CLIENTEID, NOME, EMAIL)
VALUES (2, 'Ryan Silva', 'ryansilva@gmail.com');

INSERT INTO PRODUTOS (PRODUTOSID, NOME, CATEGORIASID, PRECO, ESTOQUE)
VALUES (1, 'Celular', 1, 2000, 2000);

INSERT INTO PRODUTOS (PRODUTOSID, NOME, CATEGORIASID, PRECO, ESTOQUE)
VALUES (2, 'Camiseta', 2, 200, 200);

INSERT INTO PEDIDOS (PEDIDOSID, CLIENTEID, DATAPEDIDO, VALORTOTAL)
VALUES (1, 1, TO_DATE('10/03/2026','DD/MM/YYYY'), 2200);

INSERT INTO PEDIDOS (PEDIDOSID, CLIENTEID, DATAPEDIDO, VALORTOTAL)
VALUES (2, 2, TO_DATE('10/03/2026','DD/MM/YYYY'), 4000);

INSERT INTO ITENSPEDIDOS (ITEMID, PEDIDOSID, PRODUTOSID, QUANTIDADE, PRECOUNITARIO)
VALUES (1, 1, 1, 1, 2000);

INSERT INTO ITENSPEDIDOS (ITEMID, PEDIDOSID, PRODUTOSID, QUANTIDADE, PRECOUNITARIO)
VALUES (2, 1, 2, 1, 200);
